global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'benchmark-monitor'

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # Port interne Prometheus

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']  # Port interne Docker (expos√© 9101 externe)

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']  # Port interne Docker

  - job_name: 'variant-a-jersey'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          variant: 'A'
          framework: 'jersey'

  - job_name: 'variant-c-springmvc'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']
        labels:
          variant: 'C'
          framework: 'spring-mvc'

  - job_name: 'variant-d-springdata'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8082']
        labels:
          variant: 'D'
          framework: 'spring-data-rest'
